### ISSUE TITLE
Redmi AX5

### ISSUE THREAD

**Issue by pexcn** [openwrt-dev/openwrt-ipq60xx#1]
I have a Redmi AX5, but I haven't upgraded the RAM, maybe support for it will be added in the future, maybe not. So backup some necessary information here.

[ax5_stock_firmware_boot.log](https://github.com/openwrt-dev/openwrt-ipq60xx/files/13321205/ax5_stock_firmware_boot.log)
[ax5-bdf.zip](https://github.com/openwrt-dev/openwrt-ipq60xx/files/13321322/ax5-bdf.zip)

**UPDATE ON 20240105**
[ax5-cn-and-intl-bdwlan.zip](https://github.com/openwrt-dev/openwrt-ipq60xx/files/13837840/ax5-cn-and-intl-bdwlan.zip)

**Comment by breeze303** [comment]
I have an ax5 that has been upgraded to 1G memory. If you need to test it, please contact me.

**Comment by breeze303** [comment]
At present, the firmware I flashed after successfully compiling can boot normally. If add luci, there will be problems.

**Comment by pexcn** [comment]
> I have an ax5 that has been upgraded to 1G memory. If you need to test it, please contact me.

You can try the firmware of Xiaomi AX1800 for flashing, it should be able to boot directly.

> At present, the firmware I flashed after successfully compiling can boot normally. If add luci, there will be problems.

What's the problem?

**Comment by breeze303** [comment]
Can't start and the LED keeps flashing.

**Comment by pexcn** [comment]
> Can't start and the LED keeps flashing.

Can you provide boot log?

**Comment by breeze303** [comment]
I made a new firmware and will see if it can boot later，if possible, I hope we can communicate in Chinese, because my English is not very good, thank you.😀

**Comment by pexcn** [comment]
可以

**Comment by breeze303** [comment]
我编译了个新的，晚点刷上去看看，要不启动的话再输出下ttl给你看看

**Comment by breeze303** [comment]
[openwrt-qualcommax-ipq60xx-xiaomi_ax1800-squashfs-nand-factory.zip](https://github.com/openwrt-dev/openwrt-ipq60xx/files/13434769/openwrt-qualcommax-ipq60xx-xiaomi_ax1800-squashfs-nand-factory.zip)
这是固件

**Comment by pexcn** [comment]
你可以试试[这里](https://github.com/openwrt-dev/ci-ipq60xx/releases/download/main/ipq60xx-generic.tar.gz)的固件，它包含luci，可以正常启动

**Comment by breeze303** [comment]
> 你可以尝试[这里](https://github.com/openwrt-dev/ci-ipq60xx/releases/download/main/ipq60xx-generic.tar.gz)的支架，它包含luci，可以正常启动

好的谢谢，我晚上试试

**Comment by breeze303** [comment]
![IMG_8748](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/c03e8ee5-df7e-4a0d-b819-63ab4165ad1d)
可以刷进了，可以分享下config看看吗？不知道是不是我make menuconfig没选好

**Comment by breeze303** [comment]
你说它每次重启不会自己启动这个问题，我似乎没有遇到，是不是已经修复了？

**Comment by pexcn** [comment]
> 你说它每次重启不会自己启动这个问题，我似乎没有遇到，是不是已经修复了？

目前只有小米AX1800发现有这个问题

**Comment by breeze303** [comment]
好吧，ax5一切正常，我改天搬个ax5选项出来，这样好看些，虽然ax1800和ax5都一样😂

**Comment by pexcn** [comment]
> 好吧，ax5一切正常，我改天搬个ax5选项出来，这样好看些，虽然ax1800和ax5都一样😂

两个型号的BDF有些区别的，你可以用这个issue里最开始提到的文件试试

**Comment by breeze303** [comment]
好的谢谢，我有空再试试

**Comment by breeze303** [comment]
你有测试过这个nss有起效吗

**Comment by pexcn** [comment]
没，有测试的具体步骤吗？

**Comment by breeze303** [comment]
好像是跑iperf3看cpu占有率，最准确是用wifi跑，但这个固件没有wifi

**Comment by pexcn** [comment]
固件是支持WiFi的，之前测过WiFi下载跑到900Mbps以上，CPU占用大概30%

**Comment by breeze303** [comment]
你发的那份刷完没有无线的选项，但软件包里能看到驱动也是奇怪

**Comment by pexcn** [comment]
日志有什么报错吗？

**Comment by breeze303** [comment]
好像没有

**Comment by breeze303** [comment]
可以看看你的无线界面吗

**Comment by pexcn** [comment]
> 好像没有

贴一下你的dmesg日志看看

> 可以看看你的无线界面吗

![wifi](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/4590439/74350e7e-bb66-432c-8cdb-429d1cfc930c)

**Comment by breeze303** [comment]
> 贴一下你的dmesg日志看看
> 
上班去了，没在家，晚上我截图下

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/893b81dd-2275-4cf4-9490-32f8c359a174)
刷你给的固件的话wifi这里是这样的

**Comment by breeze303** [comment]
> ![image](https://user-images.githubusercontent.com/122870904/285192463-898ad0dc-b6a2-4d85-ac1b-e1c7f619c609.png) 卡在这里了

貌似是wifi驱动成功后就无法启动，失败反而能启动

**Comment by pexcn** [comment]
这就不清楚了，我的AX5暂时没办法测试

**Comment by breeze303** [comment]
> 这就不清楚了，我的AX5暂时没办法测试

应该是要替换你上面的dbf才行，还是得把ax5单独区分出来和ax1800不太兼容

**Comment by pexcn** [comment]
如果换的话，要改dts，具体可以参考 https://forum.openwrt.org/t/adding-openwrt-support-for-netgear-rax120-nighthawk-ax12/75592/63

**Comment by breeze303** [comment]
> 如果换的话，要改dts，具体可以参考 https://forum.openwrt.org/t/adding-openwrt-support-for-netgear-rax120-nighthawk-ax12/75592/63

修改文件指向就行了吧，patch这些也要增加ax5的型号吧？我参考你的push记录应该就行

**Comment by pexcn** [comment]
是的，参考AX1800的提交记录

**Comment by breeze303** [comment]
[package/firmware/ipq-wifi/src/board-xiaomi_ax1800.ipq6018](https://github.com/openwrt-dev/openwrt-ipq60xx/commit/d3b0b5fd9d51f75a17de60883f59fd927f7a1f8c#diff-b1ee22a217791e4cb1617d4a19e5dbfc34bed6e0be23b541c02ddeb2d4d109f2)
这个文件是哪里提取？

**Comment by breeze303** [comment]
我发现好像不需要patch来add相关的dtb？

**Comment by pexcn** [comment]
> [package/firmware/ipq-wifi/src/board-xiaomi_ax1800.ipq6018](https://github.com/openwrt-dev/openwrt-ipq60xx/commit/d3b0b5fd9d51f75a17de60883f59fd927f7a1f8c#diff-b1ee22a217791e4cb1617d4a19e5dbfc34bed6e0be23b541c02ddeb2d4d109f2) 这个文件是哪里提取？

从原厂固件提取，再参考这个提交里提到的那个链接生成

**Comment by breeze303** [comment]
https://github.com/qca/qca-swiss-army-knife这个吗？不太会怎么用😂

**Comment by pexcn** [comment]
下载这个issue的文件解压就看到说明了，源文件都在里面

**Comment by breeze303** [comment]
适配是完成了，无线不太行，编译ax1800用这个config编译不过

> 参考 https://github.com/openwrt-dev/configs-ipq60xx

这是报错日志
[新建 文本文档.txt](https://github.com/openwrt-dev/openwrt-ipq60xx/files/13460295/default.txt)

**Comment by pexcn** [comment]
日志里没看出来什么问题。我怀疑是你的环境有问题，github actions在线编译用的就是这个config，可以编译通过。具体你可以参考下另一个库ci-ipq60xx

**Comment by breeze303** [comment]
我看看

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/9db95fc1-6e8a-480f-bf72-f014558ab2fa)
可以了，无线没反应还要修修

**Comment by pexcn** [comment]
你的红米AX5不是1G内存的？原机256MB内存必然启动不了，起码要512MB才能启动

**Comment by breeze303** [comment]
> 你的红米AX5不是1G内存的？原机256MB内存必然启动不了，起码要512MB才能启动

我有两台，一台改了一台没改

**Comment by pexcn** [comment]
没改的不能用WiFi，256MB启动会有个内核模块崩溃的，我试过了

**Comment by breeze303** [comment]
> 没改的不能用WiFi，256MB启动会有个内核模块崩溃的，我试过了

那怪不得之前Wi-Fi启动然后开不了机

**Comment by pexcn** [comment]
模块崩溃也是可以开机进系统的，只是无线没办法使用

**Comment by breeze303** [comment]
usb方面能驱动吗？自带ubs驱动？

**Comment by pexcn** [comment]
不支持，USB需要改dts并安装相关kmod才行

**Comment by breeze303** [comment]
这个我知道，kmod的话里面有驱动吗

**Comment by pexcn** [comment]
要改config把usb相关模块编译进去

**Comment by breeze303** [comment]
不修这个库了吗？

**Comment by pexcn** [comment]
还有什么问题吗？

**Comment by breeze303** [comment]
系统内重启不是无法重启吗，虽然我ax5没这问题

**Comment by breeze303** [comment]
还有就是无线速率

**Comment by pexcn** [comment]
是不是coremark编译的线程数不够？我的四线程测出来18000分

**Comment by breeze303** [comment]
有个问题想请教下
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/40055596-ea67-4779-8caf-ca6cc0392090)
为啥这个库不需要打内核补丁来添加支持，还是说内核就已经支持了所以不需要打补丁？

**Comment by pexcn** [comment]
已经不需要改这个了，应该是自动匹配的

**Comment by breeze303** [comment]
> 已经不需要改这个了，应该是自动匹配的

牛的，之前打patch打到烦

**Comment by breeze303** [comment]
![Snipaste_2023-12-05_19-36-10](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/c0bab69e-4f15-47f3-94c5-55d030888e04)
nss起效还满血爽歪歪，另一颗led能驱动起来吗？要自己找gpio值?

**Comment by pexcn** [comment]
NSS是有效的？

LED的估计你可以参考下这个 https://github.com/closewrt/wlan-ap/blob/671e0a667f7a919fd825e2a965de9a6132818b60/feeds/ipq807x/ipq807x/files/arch/arm64/boot/dts/qcom/qcom-ipq6018-xiaomi-redmi-ax5.dts

**Comment by breeze303** [comment]
> NSS是有效的？

有效，cpu都不动

**Comment by pexcn** [comment]
无线的情况下，NSS有作用吗？

**Comment by breeze303** [comment]
> 无线的情况下，NSS有作用吗？

无线的话没试过，改了1G的ax5做主路由去了，只有个没改的用来做测试😂，你可以测试下，两台电脑或者手机一台做服务端一台做客户端去跑iperf3看看cpu占用率就知道了

**Comment by pexcn** [comment]
之前测试过，无线跑到900多mbps, cpu还是占了30%左右，可能是没生效了

**Comment by breeze303** [comment]
> 之前测试过，无线跑到900多mbps, cpu还是占了30%左右，可能是没生效了

不要用路由器做iperf3的服务端或者客户端，会占用cpu，也是20%-30%左右

**Comment by pexcn** [comment]
不是路由器做客户端，是内网另一台机运行[speedtest-go](https://github.com/librespeed/speedtest-go)做的服务端

**Comment by breeze303** [comment]
> 不是路由器做客户端，是内网另一台机运行 [speedtest-go](https://github.com/librespeed/speedtest-go) 做的服务端

这样的话确实没生效

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/6b7220c8-9e0a-4e8e-93ba-09098faa56ec)
今天更新了下软件库就报错了，官方的更新有问题

**Comment by pexcn** [comment]
刚刚跟着上游更新了，GitHub Actions 正在编译，不知道有没有影响

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/3f96ce7c-9fd6-425e-90fa-e36e36339b92)
大佬想请教下这里的lan的定义是在dts哪里看的吗

**Comment by pexcn** [comment]
DTS 的 label 定义的 https://github.com/openwrt-dev/openwrt-ipq60xx/blob/ee6c6a23184030f61ae23a7672c673030083518c/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-ax1800.dts#L204

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/856b67f1-862c-4fa8-95a9-eaca24189997)
还有就是这个id是什么意思，我在适配m2的时候发现这个id是不一样的，然后无法驱动网口起来，ttl能进系统

**Comment by pexcn** [comment]
我参考 ipq807x 的，这 id 应该不用变，调整 switch_lan_bmp 和 switch_wan_bmp 应该就可以了 https://github.com/openwrt/openwrt/blob/01d1c1ad296cc71f87ea02b01b16a09fe5d933a1/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq8074-ess.dtsi#L472-L536

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/276c6d96-4ca9-4335-846c-68288dd4b76e)
那这个的端口是怎么选的？对应硬件的网口

**Comment by breeze303** [comment]
![f19abbb4f4837c0f752d0ce547fb5c16](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/3b8702ca-dee8-400e-b34c-a8aec1b66757)
m2也有了ax18应该也可以了

**Comment by pexcn** [comment]
都有现成的，可以直接用 https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/blob/master/devices/qualcommax_ipq60xx/diy/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-cmiot.dtsi

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/122870904/c1424cde-ded1-4b54-acc2-5107463a593d)
请教下这里在源码哪里修改

**Comment by pexcn** [comment]
NSS 参考 https://github.com/JiaY-shi/openwrt/commit/2f54d5e3c34d2e89710f8cae378153cac149b9bf

第二个应该是opkg，试试全局搜opkg或者distfeeds

**Comment by breeze303** [comment]
> NSS 参考 [JiaY-shi/openwrt@2f54d5e](https://github.com/JiaY-shi/openwrt/commit/2f54d5e3c34d2e89710f8cae378153cac149b9bf)
> 
> 第二个应该是opkg，试试全局搜opkg或者distfeeds

ok,感谢

**Comment by pexcn** [comment]
Redmi AX5 supported now.

**Comment by breeze303** [comment]
请教下内核升级该怎么进行，有相关案例参考吗，感谢

**Comment by pexcn** [comment]
具体我也不太懂，改版本号之后可能还要刷新补丁。我都是跟随上游的，没有特意去升级

**Comment by pexcn** [comment]
@breeze303 想问下你的兆能M2那个温控风扇是怎么整的，有这方面的资料吗？

**Comment by breeze303** [comment]
> @breeze303 想问下你的兆能M2那个温控风扇是怎么整的，有这方面的资料吗？

恩山上好像有相关资料，据我所知有两种方法，一种是买pwm温控模块接pwm风扇这样可以做到调速，第二种就是买温敏开关，但只能开启或者关闭，电源从12V引出即可

**Comment by proxer05** [comment]
![image](https://github.com/openwrt-dev/openwrt-ipq60xx/assets/62423996/d222145f-aee3-4c3d-89b2-8db30ca18fd7)
Ath11k mode 2 seems working including wifi on stock unit :)

**Comment by pexcn** [comment]
Sorry, I've been too busy recently and don't have time to test it. Maybe @breeze303 can test it?

BTW, can you briefly describe how to enable it?

**Comment by breeze303** [comment]
> ![image](https://private-user-images.githubusercontent.com/62423996/294789161-d222145f-aee3-4c3d-89b2-8db30ca18fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODMxMzgsIm5iZiI6MTcwNDY4MjgzOCwicGF0aCI6Ii82MjQyMzk5Ni8yOTQ3ODkxNjEtZDIyMjE0NWYtYWVlMy00YzNkLTg5YjItOGRiMzBjYTE4ZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzMDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OWRkZTY0ZTQ2NjNlYzVmYzhhNjY1NWMwYWE1MDMyZjRkMmRiNWY3YmEyODM5ZDA0ZGJmMDFlZGQ1MzE4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXnV7xCSPcEqIro6zlMeCpQFDzkVOR8iSL8afn5Vl38) Ath11k mode 2 seems working including wifi on stock unit :)

Can the device search for wireless signals?

**Comment by proxer05** [comment]
> Sorry, I've been too busy recently and don't have time to test it. Maybe @breeze303 can test it?
> 
> BTW, can you briefly describe how to enable it?

https://github.com/XimiAX5-WRT/openwrt-ipq60xx/commit/3e8d1ec6e1a93a87c37e5031b48e5cb66a88260a

**Comment by proxer05** [comment]
Zram will be useful

**Comment by proxer05** [comment]
It works fine on 512mb too

**Comment by pexcn** [comment]
> It works fine on 512mb too

My all ipq60xx devices has been upgraded to 1GB. 😅

**Comment by proxer05** [comment]
https://pastebin.com/raw/HTrZbvRv still should be fine. You will have more memory for Linux itself

**Comment by pexcn** [comment]
> https://pastebin.com/raw/HTrZbvRv still should be fine. You will have more memory for Linux itself

I wish more memory is used for wifi, because this firmware is used as an AP for me.

**Comment by proxer05** [comment]
> > [XimiAX5-WRT@3e8d1ec](https://github.com/XimiAX5-WRT/openwrt-ipq60xx/commit/3e8d1ec6e1a93a87c37e5031b48e5cb66a88260a)
> 
> Okay, I know. but I don't have a 256MB ipq60xx device, so it doesn't seem to make much sense to me.
> Is there a way to add a menuconfig option to allow users to select it?
> 

We can make another subtarget which uses modified dtsi

**Comment by pexcn** [comment]
I think this is a bit too much trouble. 😂It’s better to upgrade the memory to 1G.

BTW, I hope that the discussion related to this topic can be moved to this issue https://github.com/openwrt-dev/ci-ipq60xx/issues/3, so close this.
